# dbt profiles.yml
# This file configures how dbt connects to your data warehouse
# Copy this file to ~/.dbt/profiles.yml or keep it in your project root

bikeshare_analytics:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"  # Use environment variable
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'SYSADMIN') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'BIKESHARE_DB') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'BIKESHARE_WH') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'RAW') }}"
      threads: 4
      keepalives_idle: 240
      search_path: "BIKESHARE_DB.RAW"
      
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"  # Use environment variable
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'SYSADMIN') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'BIKESHARE_DB') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'BIKESHARE_WH') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'RAW') }}"
      threads: 8
      keepalives_idle: 240
      search_path: "BIKESHARE_DB.RAW"

  target: dev 